name: Check HTTP Status Code

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check_status_code:
    runs-on: ubuntu-latest

    steps:
      - name: Check HTTP Status Code
        run: |
          status_code=$(curl -kL -s -o /dev/null -w "%{http_code}" https://www.juntekim.com)
          if [ "$status_code" -ne 200 ]; then
            echo "The website returned status code $status_code"
            exit 1
          else
            echo "The website returned status code 200"
          fi
      
      - name: Check HTTP Status Code and Redirect for /newsletter
        run: |
          final_url=$(curl -kLs -o /dev/null -w "%{url_effective}" https://www.juntekim.com/newsletter)
          status_code=$(curl -kLs -o /dev/null -w "%{http_code}" https://www.juntekim.com/newsletter)
          
          if [ "$status_code" -ne 200 ]; then
            echo "The /newsletter endpoint returned status code $status_code"
            exit 1
          elif [ "$final_url" != "https://www.juntekim.com/newsletter" ]; then
            echo "The final redirected URL was $final_url instead of https://www.juntekim.com/newsletter"
            exit 1
          else
            echo "The /newsletter endpoint returned status code 200 and the final URL was correct"
          fi

      - name: Check HTTP Status Code and Redirect for /ynab_calls
        run: |
          final_url=$(curl -k -Ls -o /dev/null -w "%{url_effective}" http://www.juntekim.com/ynab_calls)
          status_code=$(curl -k -Ls -o /dev/null -w "%{http_code}" http://www.juntekim.com/ynab_calls)
          
          # Normalize the final URL by removing a trailing slash if present
          normalized_url=${final_url%/}

          if [ "$status_code" -ne 200 ]; then
            echo "The /ynab_calls endpoint returned status code $status_code"
            exit 1
          elif [ "$normalized_url" != "https://www.juntekim.com/ynab_calls" ]; then
            echo "The final redirected URL was $final_url instead of https://www.juntekim.com/ynab_calls"
            exit 1
          else
            echo "The /ynab_calls endpoint returned status code 200 and the final URL was correct"
          fi

