name: Check HTTP Status Code and Public IP

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check_public_ip:
    runs-on: self-hosted  # This job will run on a self-hosted runner

    steps:
      - name: Check Public IP
        run: |
          EXPECTED_IP="81.97.23.124"
          CURRENT_IP=$(curl -s ifconfig.me)
          if [ "$CURRENT_IP" == "$EXPECTED_IP" ]; then
              echo "Public IP is still $CURRENT_IP."
          else
              echo "The public IP has changed. Current IP: $CURRENT_IP."
              exit 1
          fi